version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.2
   steps:
     - checkout
     - run:
         name: Restore packages
         command: dotnet restore ./NetCoreBoilerplateBE/
     - run:
         name: Build App
         command: dotnet build ./NetCoreBoilerplateBE/
     - run:
         name: Run Unit Test
         command: dotnet test ./NetCoreBoilerplateBE/NetCoreBoilerPlate.Api.Test/ --no-build
     - run:
         name: Run Unit Test
         command: dotnet test ./NetCoreBoilerplateBE/NetCoreBoilerPlate.Service.Test/ --no-build --logger "trx;LogFileName=../../../xunit-output.xml"
     - run:
         name: Run Unit Test
         command: dotnet test ./NetCoreBoilerplateBE/NetCoreBoilerPlate.Repo.Test/ --no-build --logger "trx;LogFileName=../../../xunit-output.xml"
     - run:
         name: Run Unit Test
         command: dotnet test ./NetCoreBoilerplateBE/NetCoreBoilerPlate.Logger.Test/ --no-build --logger "trx;LogFileName=../../../xunit-output.xml"
